name: "build Web Project"
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  cache-installation-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install && pnpm build

      - name: Install zip
        run: sudo apt-get install zip -y

      - name: Compress files to zip
        run: zip -r dist.zip dist/

      - name: Compress files to tar.gz
        run: tar -zcvf dist.tar.gz dist/

      - uses: actions/upload-artifact@v4
        with:
          name: music-web
          path: dist.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:

          # 上传的文件路径，可以使用通配符
          files: |
            dist.tar.gz
            dist.zip
          # GitHub token 用于进行上传操作
          token: ${{ secrets.GITHUB_TOKEN }}
          # 发布 tag 名称
          # tag_name: ${{ github.event.release.tag_name }}
          draft: true
